### ISSUE TITLE
Use fractional count of 9th mag stars > 3.0 criterion for ERs

### ISSUE THREAD

**Issue by taldcroft** [sot/sparkles#37]
The FDB checklist requirement is:
ACA-046 | Magnitude | X | X | Perigee catalogs have 3 or more GS magnitude 9.0 or brighter

That was written forever-ago and does not consider temperature dependence.  I think we can interpret magnitude to be "temperature-corrected" magnitude and "3 or more" to be the fractional count.

**Comment by jeanconn** [comment]
Agreed.  Though not quite clear on interpret ... "3 or more" to be the fractional count?  I assume that just means to set a check threshold on fractional count to about 3.  It also looks like using the ER adjusted fractional count would be significantly more conservative that the the current guidance (and I'm fine with more conservative, just keeping visibility on it).

In [53]: guide_count([9.0, 9.0, 9.0, 10.3, 10.3, 10.3], -12.96, is_ER=True)
Out[53]: 2.9978860255561708

I was trying to keep this at mag=9.0 for the quick release because planners wouldn't necessarily be able to see they had satisfied the fractional count (or how to satisfy it), but with the next planned release red and orange warnings should be visible to them and I won't have that concern.

**Comment by taldcroft** [comment]
Good point.  My intent was to match current behavior so I was off by one index.  The new behavior is slightly less conservative, except that we will mostly be planning at temps above -10.9C so it probably washes out.  See #38.

**Comment by jeanconn** [comment]
Done in #40
