### ISSUE TITLE
Exceptions on the MATLAB side?

### ISSUE THREAD

**Issue by jeanconn** [sot/sparkles#78]
So, the reason I was confused by 

https://github.com/sot/sparkles/blob/1828d30ed712e7daa8a51e52f95478a4112fafaa/sparkles/roll_optimize.py#L321

was that I didn't see a reason to override the requested behavior.  I'm figuring out that the point was to pass back the exceptions here:

https://github.com/sot/sparkles/blob/1828d30ed712e7daa8a51e52f95478a4112fafaa/sparkles/core.py#L129

even for the primary use case of ORViewer calling that code.  I didn't realize we were doing anything with exceptions on the MATLAB side yet.  So what is the MATLAB side doing with the exceptions now and how will we set up an integration test for that (now that https://github.com/sot/sparkles/pull/69/commits/a5a5691d02e6d51766074f2dd19699df01efacc8 will fix the one broken roll-options catalog)?

**Comment by taldcroft** [comment]
The sparkles code now provides a method and API for handling exceptions in the Python code.  It's up to @jskrist to determine how to use it. 

The point of how to test it is interesting.  It's easy enough in a unit test, just pass in a bad value to `run_aca_review`:
https://github.com/sot/sparkles/blob/1828d30ed712e7daa8a51e52f95478a4112fafaa/sparkles/tests/test_review.py#L153

But how to do that in the context of ORviewer is outside my expertise, but James will figure out a way to his satisfaction.  

Note that the exception does not need to occur in `get_aca_catalog` here to be a valid test.  With the proseco API change, `get_aca_catalog` is just one bit out of a lot of code that might raise an exception.  There is nothing at all special about it now.  Previously it was special because if it failed then you would not have clue that the failure was actually in `get_aca_catalog` because the fail would be some unrelated downstream fail.

BTW, not sure what you mean by "requested behavior".  At this point in the code (near the first referenced line) there is no user input on exception handling.  In both proseco and sparkles the `raise_exc` input is not passed into the "real work" functions.

**Comment by jeanconn** [comment]
"BTW, not sure what you mean by "requested behavior". At this point in the code (near the first referenced line) there is no user input on exception handling. In both proseco and sparkles the `raise_exc` input is not passed into the "real work" functions."

By "requested behavior" I meant that without the override at kwargs['raise_exc'] = True, I thought the raise_exc value that was passed to the "original" get_aca_catalog() would be passed to the get_aca_catalog calls used for the roll options.

**Comment by jeanconn** [comment]
And yes, understood regarding "Note that the exception does not need to occur in `get_aca_catalog` here to be a valid test.".   

I was wondering specifically, however, if we cared about having information on one roll option if one of the others threw an exception.  Hopefully not a frequent enough case to care.

**Comment by jeanconn** [comment]
And regarding "The sparkles code now provides a method and API for handling exceptions in the Python code. It's up to @jskrist to determine how to use it." I suppose I should have opened this as a proseco issue where I have convenient labels for MATLAB and "testing".

**Comment by taldcroft** [comment]
> I thought the raise_exc value that was passed to the "original" get_aca_catalog() would be passed to the get_aca_catalog calls used for the roll options.

Negative.  As mentioned that arg is swallowed early and does not get into call_args nor anywhere in the ACATable object.

> I was wondering specifically, however, if we cared about having information on one roll option if one of the others threw an exception. Hopefully not a frequent enough case to care.

I am not concerned about that case in practice.

> I suppose I should have opened this as a proseco issue where I have convenient labels for MATLAB and "testing".

You have rights and permission to make labels!

**Comment by jeanconn** [comment]
"Negative. As mentioned that arg is swallowed early and does not get into call_args nor anywhere in the ACATable object."

Oh.  Then I'm confused again about why this line was needed  https://github.com/sot/sparkles/blob/1828d30ed712e7daa8a51e52f95478a4112fafaa/sparkles/roll_optimize.py#L321
and will have to fiddle with it some tomorrow.

**Comment by taldcroft** [comment]
AFAIK there are no open and actionable code issues related to exception handling as discussed in this thread.  @jeanconn - if you have something in mind you can open a new issue.
